Gemfile, Gemfile.lock, app/models/cat.rb, app/views/cats/index.html.erb, db/migrate/20160229232843_add_attributes_to_cat.rb, db/schema.rb, spec/features/user_can_view_cats_spec.rb, spec/models/cat_spec.rb
Add description, price, and image to Cat model
=> Add columns to cat

Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/models/cat.rb, app/models/category.rb, app/views/categories/show.html.erb, config/routes.rb, db/migrate/20160229215751_create_categories.rb, db/migrate/20160301000508_add_category_id_to_cat.rb, db/schema.rb, spec/features/user_can_view_cats_spec.rb, spec/features/user_views_cats_by_category_spec.rb, spec/models/cat_spec.rb, spec/models/category_spec.rb, spec/rails_helper.rb
added category model test, validations, controller and views for show
=> Cat categories

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/controllers/categories_controller.rb, app/controllers/cats_controller.rb, app/views/categories/show.html.erb, app/views/cats/index.html.erb, app/views/layouts/application.html.erb, app/views/partials/_category_drop.html.erb, app/views/partials/_each_cat.html.erb
- Created partials for iteration of cats
- Drop down for filtering of cats by category
- Color scheme based on Compatible by joy_of_summer
- Edited profile picture placement, description and age in cat profiles
=> Style cat index and category show

app/controllers/application_controller.rb, app/controllers/carts_controller.rb, app/models/cart.rb, app/views/carts/show.html.erb, app/views/cats/index.html.erb, app/views/layouts/application.html.erb, app/views/partials/_each_cat.html.erb, config/routes.rb, spec/features/user_adds_items_to_cart_spec.rb, spec/models/cart_spec.rb
Cart model and show page implemented
Cart based off of session
Custom route added for viewing a cart
Link to Cart added on cat index page, will be removed once styling with navbar merged
@amaxwellblair @cheljoh I think adding to cart implementation is complete, but a close set of eyes on the whole thing definitely wouldn't hurt.
=> Add ability to add cats to cart

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/dashboard/show.html.erb, app/views/layouts/application.html.erb, app/views/users/new.html.erb, config/routes.rb, db/migrate/20160301213911_create_users.rb, db/schema.rb, spec/features/visitor_creates_account_spec.rb, spec/models/user_spec.rb
Links to log in/out/create accounts appear in navbar based on status
If a visitor added items to their cart, they still appear after
creating an account
=> Add ability for visitors to create account

app/controllers/carts_controller.rb, app/models/cart.rb, app/views/carts/show.html.erb, app/views/layouts/application.html.erb, spec/features/user_tries_to_add_cat_to_cart_more_than_once_spec.rb, spec/models/cart_spec.rb, spec/spec_helper.rb
doubleclick? will check for a user clicking on a cat more than once
=> Add doubleclick method to cart

app/assets/stylesheets/application.css, app/controllers/orders_controller.rb, app/models/order.rb, app/models/user.rb, app/views/orders/index.html.erb, config/routes.rb, db/migrate/20160301225451_create_orders.rb, db/schema.rb, spec/features/user_views_past_orders_spec.rb, spec/models/order_spec.rb, spec/models/user_spec.rb
Orders belong to users
Orders index shows all orders belonging to logged in user
=> Add ability for authenticated user to see orders

app/assets/stylesheets/application.css, app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/views/carts/show.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, config/routes.rb, spec/features/user_can_check_out_spec.rb, spec/models/order_spec.rb
Order index shows a list of all previous orders, links to show page
Order show page shows order statistics and specific cats
Styled order show and index pages
=> User places Order

app/models/cat.rb, app/views/landing/show.html.erb, spec/features/user_can_rent_a_random_cat_spec.rb, spec/models/cat_spec.rb
Add random cat to cart functionality
=> Random cat

app/assets/javascripts/application.js, app/views/layouts/application.html.erb, app/views/partials/_navbar_list.html.erb, spec/features/user_adds_items_to_cart_spec.rb, spec/features/user_can_log_in_and_out_spec.rb, spec/features/user_can_remove_cats_from_cart_spec.rb, spec/features/visitor_creates_account_spec.rb
Slides out from right when screen is collapsed
Moved ul to partial, as it was listed twice.
Chelsea and Allan - you might look at it in the front end in addition to a code review - it's functional but may not be the design you're going for.
=> Add collapsible navbar

app/controllers/orders_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/cart.rb, app/views/layouts/application.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, spec/features/user_adds_items_to_cart_spec.rb, spec/features/user_can_check_out_spec.rb, spec/features/user_can_log_in_and_out_spec.rb, spec/features/user_views_cats_by_category_spec.rb, spec/features/user_views_past_orders_spec.rb, spec/features/view_past_order_spec.rb, spec/features/visitor_creates_account_spec.rb, spec/spec_helper.rb
Added sad path tests  with flash messages and the necessary logic in the controllers and (temporarily) the views.
Added log_in_user method to spec helper.
=> Implement Sad Paths

app/assets/javascripts/application.js, app/controllers/carts_controller.rb, app/views/layouts/application.html.erb, spec/features/user_adds_items_to_cart_spec.rb
Unless the cat is already in your cart
=> Flash message when adding to cart

app/controllers/admin/base_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, config/routes.rb, db/migrate/20160303213649_add_role_to_user.rb, db/schema.rb, spec/features/admin_logs_in_spec.rb, spec/spec_helper.rb
Add role to user table to allow for default and admin
Add admin controller and views folder
Admins are redirected to admin dashboard when logged in
=> Add admin login functionality

Gemfile, Gemfile.lock, app/views/admin/users/show.html.erb, spec/features/admin_visits_admin_dashboard_spec.rb, test/test_helper.rb
Install mocha gem to allow for stubbing of users
Test that non-admin users/unregistered visitors cannot view admin paths
Include "Admin Dashboard" header on dashboard
=> Test admin authorization

app/assets/javascripts/application.js, app/controllers/admin/cats_controller.rb, app/models/cat.rb, app/views/admin/cats/new.html.erb, config/routes.rb, db/migrate/20160304000423_remove_imagefrom_cats.rb, db/migrate/20160304000529_add_image_to_cats.rb, db/schema.rb, spec/features/admin_creates_an_item_spec.rb, spec/features/user_can_view_cats_spec.rb, spec/models/cart_spec.rb, spec/models/cat_spec.rb, spec/spec_helper.rb
Added form for new cat and cat creation functionality
Deleted previous image column on cats table
Added new image column to cats table with a default image
Most tests for presence of all necessary information are model tests,
not feature tests
"Create Cat" button on form still needs to be styled - css has changed,
so didn't do it yet to avoid merge conflicts
=> Admin creates a cat

app/assets/stylesheets/custom_stylesheet.css, app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, app/models/cat_order.rb, app/models/order.rb, app/views/admin/orders/index.html.erb, app/views/carts/show.html.erb, app/views/partials/_order.html.erb, db/migrate/20160305230000_add_dates_to_order.rb, db/schema.rb, db/seeds.rb, spec/features/user_creates_a_reservation_spec.rb, spec/models/cat_order_spec.rb
Orders can now be set for future dates.
Reservations cannot overlap.
Overdue is now a status section on admin dashboard
=> Reservations

Gemfile, Gemfile.lock, app/assets/stylesheets/custom_stylesheet.css, app/controllers/articles_controller.rb, app/services/articles.rb, app/views/articles/index.html.erb, config/routes.rb
Created reddit data scrap with vote ranking system
Article view page and controller
Article styling
=> Create NPRrr article stream

app/controllers/admin/orders_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/views/admin/orders/index.html.erb, app/views/carts/show.html.erb, app/views/partials/_each_cat.html.erb, app/views/partials/_order.html.erb, spec/features/admin_views_indv_order_spec.rb, spec/features/user_can_check_out_spec.rb, spec/features/user_cart_empty_after_checkout_spec.rb, spec/features/user_creates_a_reservation_spec.rb, spec/features/view_past_order_spec.rb, spec/models/order_spec.rb, spec/spec_helper.rb
Reservation end date must be at least one day after start date
When admin cancels order, start and end date are removed so cat can be rented on those dates
Bug preventing renting fixed
=> More reservation functionality

app/controllers/admin/cats_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/application_controller.rb, app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/cart.rb, app/models/cat.rb, app/models/order_processor.rb, app/models/user.rb, app/views/admin/orders/index.html.erb, app/views/cats/show.html.erb, app/views/partials/_each_order.html.erb, app/views/partials/_navbar_list.html.erb, app/views/partials/_order_update.html.erb, config/routes.rb, spec/features/user_can_log_in_and_out_spec.rb, spec/models/cart_spec.rb, spec/models/cat_spec.rb
=> 70 refactor 3 7

README.md, app/controllers/cats_controller.rb, app/controllers/reviews_controller.rb, app/models/cat.rb, app/models/review.rb, app/models/user.rb, app/views/cats/show.html.erb, app/views/partials/_review_form.html.erb, app/views/partials/_review_table.html.erb, config/routes.rb, db/migrate/20160308025500_create_reviews.rb, db/migrate/20160308225524_add_user_to_reviews.rb, db/schema.rb, spec/features/user_rates_a_cat_spec.rb, spec/models/cat_spec.rb, spec/models/review_spec.rb
Implemented cat reviews. Registered users can now review a cat. Unregistered users cannot review cats, but they are able to see the cat reviews from registered users. Added the necessary models, views, and migrations for cat reviews.
=> 69 cat reviews
